/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.java858.todoapp.gui;

import it.java858.todoapp.entity.Categoria;
import it.java858.todoapp.service.CategoriaService;
import javax.swing.JOptionPane;

/**
 *
 * @author tss
 */
public class CategoriaEdit extends javax.swing.JDialog {

    private Categoria categoria;

    /**
     * Creates new form CategoriaEdit
     */
    public CategoriaEdit(Categoria categoria, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init(categoria);
    }

    public CategoriaEdit(Categoria categoria, java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init(categoria);
    }
    
    //visualizza a categoria
    public void modelToview(){
        txtnome.setText(categoria.getNome());
    }
    
    //salva info video to categoria
    public void viewTomodel(){
        categoria.setNome(txtnome.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmdsalva = new javax.swing.JButton();
        cmdannulla = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("nome categoria:");

        cmdsalva.setText("salva");
        cmdsalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvaActionPerformed(evt);
            }
        });

        cmdannulla.setText("annulla");
        cmdannulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdannullaActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Creazione modifica Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdsalva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdannulla))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsalva)
                    .addComponent(cmdannulla))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdsalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvaActionPerformed
        viewTomodel();
        CategoriaService.save(categoria);
        //JOptionPane.showMessageDialog(this, "Categoria salvata");
        close();
    }//GEN-LAST:event_cmdsalvaActionPerformed

    private void cmdannullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdannullaActionPerformed
        close();        // TODO add your handling code here:
    }//GEN-LAST:event_cmdannullaActionPerformed

    private void close() {
        this.setVisible(false);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdannulla;
    private javax.swing.JButton cmdsalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables

    private void init(Categoria categoria) {
        this.categoria=categoria;
        txtnome.setText(categoria.getNome());
        modelToview();
    }
}
